[package]
name = "pocket-throne"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
eldenring = {
	git = "https://github.com/vswarte/fromsoftware-rs.git",
	rev = "59fbd3b3b7daaf14aca47c9f73530493dba6bc79" # supports ER 1.17.1
}
fromsoftware-shared = {
	git = "https://github.com/vswarte/fromsoftware-rs.git",
	rev = "59fbd3b3b7daaf14aca47c9f73530493dba6bc79" # supports ER 1.17.1
}
glam = ">= 0.30"

[profile.dev]
# Crash early
panic = "abort"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
